name: Deploy Pages project
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project name to deploy'
        required: true

jobs:
  deploy_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./deploy.sh
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      CF_EMAIL: ${{ secrets.CF_EMAIL }}
      PROJECT_NAME: ${{ github.event.inputs.project_name || github.event.client_payload.project_name }}